name: Daily ETL Pipeline

on:
  schedule:
    # Run every day at 6:00 AM UTC (market close time)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  etl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ETL Pipeline
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        python etl_script.py
        
    - name: Commit and push data updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m "🤖 Automated ETL update - $(date -u +'%Y-%m-%d %H:%M UTC')"
        git push
        
    - name: Notify on success
      if: success()
      run: |
        echo "✅ ETL pipeline completed successfully at $(date -u)"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ ETL pipeline failed at $(date -u)"
        # You can add Slack/Discord notifications here
