# Database Configuration
DB_HOST = "db.yejdhlozdggblspyrure.supabase.co"
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASS = "Livescan1!"
DB_PORT = "5432"

# Note: Replace the values above with your actual database credentials
# Streamlit Cloud will securely store these values
