# Database Configuration
DB_HOST = "localhost"
DB_NAME = "intellivest"
DB_USER = "postgres"
DB_PASS = "Livescan1"
DB_PORT = "5432"

# Note: Replace the values above with your actual database credentials
# Streamlit Cloud will securely store these values
