# Database Configuration - Using Supabase Connection Pooler
DATABASE_URL = "postgresql://postgres.yejdhlozdggblspyrure:Livescan1!@aws-1-us-east-2.pooler.supabase.com:6543/postgres"

# Note: Replace the values above with your actual database credentials
# Streamlit Cloud will securely store these values
