# Streamlit Cloud Secrets Configuration
# This file contains sensitive database connection information
# DO NOT commit this file to version control

# Supabase Connection Pooler URL (IPv4 compatible)
DATABASE_URL = "postgresql://postgres.yejdhlozdggblspyrure:Livescan1!@aws-1-us-east-2.pooler.supabase.com:6543/postgres"

# Alternative individual parameters (if needed)
# DB_HOST = "aws-1-us-east-2.pooler.supabase.com"
# DB_NAME = "postgres"
# DB_USER = "postgres.yejdhlozdggblspyrure"
# DB_PASS = "Livescan1!"
# DB_PORT = "6543"
